services:
  postgres:
    image: postgres:15
    container_name: ag_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agency
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: ag_mongo
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: ag_redis
    networks:
      - app-network

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: ag_gotenberg
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ag_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    environment:
      PGHOST: postgres
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: agency
      PGPORT: 5432
      MONGO_URI: mongodb://mongo:27017/advertising_agency
      REDIS_URL: redis://redis:6379
      GOTENBERG_URL: http://gotenberg:3000
      PORT: 3000
    depends_on:
      - postgres
      - mongo
      - redis
      - gotenberg
    networks:
      - app-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ag_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      # - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  mongodata:
